name: Validate, Build, and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # Skip for dist PRs
    if: github.event_name != 'pull_request' || github.head_ref != 'update-dist-artifact'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: dropdown-list-badge-test:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Verify dist folder in image
        run: docker run --rm dropdown-list-badge-test:latest ls -l dist

      - name: Start server
        run: |
          docker run --name dropdown-list-badge-server -d -p 5000:5000 dropdown-list-badge-test:latest npx serve -l 5000 .
          sleep 5

      - name: Run Playwright tests
        run: |
          docker run --rm --network host \
            -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/tests/__snapshots__:/app/tests/__snapshots__ \
            -v ${{ github.workspace }}/tests/test-results:/app/tests/test-results \
            -v ${{ github.workspace }}/tests/html-report:/app/tests/html-report \
            dropdown-list-badge-test:latest npx playwright test --config=tests/playwright.config.ts

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: tests/html-report

      - name: Stop server
        run: docker rm -f dropdown-list-badge-server || true

      - name: Copy dist from Docker image
        run: |
          id=$(docker create dropdown-list-badge-test:latest)
          docker cp $id:/app/dist ./dist-artifact
          docker rm $id

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist-artifact

  commit_dist:
    runs-on: ubuntu-latest
    needs: [build_and_test, codeql-analysis]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist-artifact

      - name: Copy dist artifact into repo
        run: |
          rm -rf dist
          mv dist-artifact dist

      - name: Allow dist for CI
        run: echo "!dist/" >> .gitignore

      - name: Show git status for debug 1
        run: git status

      - name: Create Pull Request for dist update
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}        
          commit-message: "chore: Build and commit dist folder for HACS"
          branch: update-dist-artifact
          title: "Update dist folder from CI"
          body: "Automated update of dist folder after successful build and test."
          base: main
          add-paths: dist/
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

  tag_on_version_change:
    runs-on: ubuntu-latest
    needs: commit_dist
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version.json changed
        id: version_changed
        run: |
          if git show --name-only --pretty="" HEAD | grep -q "^version.json$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if version.json not changed
        if: steps.version_changed.outputs.changed == 'false'
        run: |
          echo "version.json not changed, skipping tag/release."
          exit 0

      - name: Read version from version.json
        id: version
        run: |
          VERSION=$(jq -r .version version.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check
        run: |
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag and release
        if: steps.check.outputs.tag_exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codeql-analysis:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
        - language: javascript-typescript
          build-mode: none
    # Skip codeql for dist PRs
    if: github.event_name != 'pull_request' || github.head_ref != 'update-dist-artifact'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        echo 'If you are using a "manual" build mode for one or more of the' \
          'languages you are analyzing, replace this with the commands to build' \
          'your code, for example:'
        echo '  make bootstrap'
        echo '  make release'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
